apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bifrost
  namespace: proxy
  annotations:
    tailscale.com/hostname: "llm-proxy"
    tailscale.com/proxy-class: "avoid-slow-nodes"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - llm-proxy
  rules:
    - host: llm-proxy
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bifrost
                port:
                  number: 8080
