apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-s3-cache
  namespace: pcloud-s3
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 50Gi
