apiVersion: litestream.mytools.nakatanakatana.app/v1alpha1
kind: LitestreamReplica
metadata:
  name: feed-reader-db-debug-source
  namespace: app
spec:
  replica:
    type: s3
    s3:
      endpoint: http://storage:8010
      bucket: feed-reader
      path: feed-reader.db
      credentials:
        accessKeyID:
          secretKeyRef:
            name: feed-reader-storage
            key: access_key
        secretAccessKey:
          secretKeyRef:
            name: feed-reader-storage
            key: access_secret
---
apiVersion: litestream.mytools.nakatanakatana.app/v1alpha1
kind: Litestream
metadata:
  name: feed-reader-db-debug
  namespace: app
spec:
  image:
    repository: litestream/litestream
    tag: 0.5.17
    digest: sha256:4b02b9859a6b6b4087d8b8944e15f7e984bd7957cba322bbeee38b0e27b9656a
    pullPolicy: IfNotPresent
  injection:
    targetContainer: sqlite3
    volume: data
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: OnRootMismatch
  databases:
    - name: feed-reader
      path: /data/feed-reader.db
      restore:
        replicaRef:
          name: feed-reader-db-debug-source
        ifDatabaseExists: skip
        ifReplicaMissing: fail
        integrityCheck: quick
