apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-ci-tekton-sync
  namespace: ci
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "components/tekton"
  prune: true
  timeout: 2m
  kubeConfig:
    secretRef:
      name: vc-vcluster
      key: config
  dependsOn:
    - name: vcluster-ci-sync
