apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-agent-sync
  namespace: agent
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "clusters/vcluster-agent"
  prune: true
  timeout: 2m
  kubeConfig:
    secretRef:
      name: vc-vcluster
      key: config
  dependsOn:
    - name: vcluster-agent
      namespace: flux-system
