apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-app
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: app
  path: "components/vcluster/base"
  prune: true
  timeout: 1m
  patches:
    - target:
        kind: HelmRelease
        name: vcluster
      patch: |
        - op: add
          path: /spec/values
          value:
            controlPlane:
              service:
                annotations:
                  tailscale.com/expose: "true"
                  tailscale.com/hostname: "vcluster-app"
            exportKubeConfig:
              server: "https://vcluster.app.svc.cluster.local:443"
            networking:
              replicateServices:
                fromHost:
                  - from: couchdb/couchdb-svc-couchdb
                    to: obsidian-clippings-feed/couchdb-svc-couchdb
                  - from: tailscale/storage-clusterip
                    to: nostr/storage
            sync:
              fromHost:
                secrets:
                  enabled: true
                  mappings:
                    byName:
                      "app/obsidian-secret": "obsidian-clippings-feed/obsidian-secret"
                      "app/nostr-config": "nostr/nostr-config"
                      "app/nostr-credentials": "nostr/nostr-credentials"
                      "app/nostr-storage": "nostr/nostr-storage"
