apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-agent
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: agent
  path: "components/vcluster/base"
  prune: true
  timeout: 1m
  patches:
    - target:
        kind: HelmRelease
        name: vcluster
      patch: |
        - op: add
          path: /spec/values
          value:
            controlPlane:
              service:
                annotations:
                  tailscale.com/expose: "true"
                  tailscale.com/hostname: "vcluster-agent"
                spec:
                  type: LoadBalancer
            exportKubeConfig:
              server: "https://vcluster.agent.svc.cluster.local:443"
              additionalSecrets:
                - name: vcluster-agent-kubeconfig
                  namespace: flux-system
