apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: vcluster
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - lb.yaml
configMapGenerator:
  - name: vcluster
    files:
      - values.yaml
  - name: vcluster-policy
    files:
      - policy-values.yaml
configurations:
  - kustomizeconfig.yaml
