apiVersion: v1
kind: Service
metadata:
  name: vcluster-loadbalancer
  namespace: vcluster
spec:
  selector:
    app: vcluster
    release: vcluster
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer
