apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-resources
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/home/resources
  dependsOn:
    - name: cluster-controllers
  prune: true
  healthChecks:
    - apiVersion: litestream.mytools.nakatanakatana.app/v1alpha1
      kind: Litestream
      name: feed-reader-db-debug
      namespace: app
  timeout: 5m
