apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-gpu-device-plugin
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  path: components/amd-gpu-device-plugin
  prune: true
  timeout: 5m
