apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-ingress
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cloudflare-tunnel-ingress
  path: "components/cloudflare-tunnel-ingress"
  prune: true
  timeout: 1m
