apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pcloud-s3
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pcloud-s3
  path: "components/pcloud-s3"
  prune: true
  timeout: 1m
