apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pipelines-as-code
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pipelines-as-code
  path: "components/pipelines-as-code"
  prune: true
  timeout: 1m
