apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vcluster
  namespace: vcluster
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: vcluster
      version: '0.26.0'
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  releaseName: vcluster
  valuesFrom:
    - kind: ConfigMap
      name: vcluster
    - kind: ConfigMap
      name: vcluster-policy
