controlPlane:
  distro:
    k8s:
      enabled: true
      apiServer:
        extraArgs:
          - --oidc-issuer-url=https://accounts.google.com
          - --oidc-client-id=613184563802-3ibtt184darm98idtv2kjcph6ol3nuga.apps.googleusercontent.com
      image:
        registry: ghcr.io
        repository: loft-sh/kubernetes
        tag: v1.36.3@sha256:00adad47a4441b13690428a5a596cd71ef2211b3674c1918e1c731bc49653ead
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
  service:
    enabled: true
    spec:
      type: ClusterIP
  proxy:
    extraSANs:
      - rpi
      - rk1
      - rk2
      - rk3
      - rk4
      - vcluster-agent
      - vcluster-sandbox
      - vcluster-app
      - vcluster-ci
      - vcluster.agent.svc.cluster.local
      - vcluster.sandbox.svc.cluster.local
      - vcluster.app.svc.cluster.local
      - vcluster.ci.svc.cluster.local
  coredns:
    enabled: true
  statefulSet:
    image:
      registry: ghcr.io
      repository: loft-sh/vcluster-oss
      tag: 0.36.0@sha256:54b8fdbb60375ae577cf598567a1ec6bb5957f1d8604b6bab0debee1da2532ef
    env:
      - name: LOFT_LOG_LEVEL
        value: warn
    resources:
      limits:
        ephemeral-storage: 2Gi
        memory: 2Gi
      requests:
        ephemeral-storage: 400Mi
        cpu: 200m
        memory: 256Mi
    highAvailability:
      replicas: 1
    security:
      podSecurityContext: {}
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
        runAsGroup: 0
    persistence:
      volumeClaim:
        enabled: auto
        retentionPolicy: Retain
        size: 2Gi
        storageClass: ""
        accessModes: ["ReadWriteOnce"]
sync:
  toHost:
    ingresses:
      enabled: true
  fromHost:
    ingressClasses:
      enabled: true
    secrets:
      enabled: false
    configMaps:
      enabled: false
exportKubeConfig:
  server: "https://vcluster-agent:443"
  insecure: false
experimental:
  deploy:
    vcluster:
      manifests: |-
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: oidc-cluster-admin
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: https://accounts.google.com#105210177226998324921
