controlPlane:
  distro:
    k3s:
      enabled: true
      extraArgs:
        - --tls-san=rk1 --tls-san=rk2 --tls-san=rk3 --tls-san=rk4
        - --kube-apiserver-arg=oidc-issuer-url=https://accounts.google.com
        - --kube-apiserver-arg=oidc-client-id=829062615345-ol62l3fri5kpki5dv7400eq88ml0pu59.apps.googleusercontent.com
      image:
        repository: rancher/k3s
        tag: v1.32.2-k3s1
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
  proxy:
    extraSANs:
      - rk1
      - rk2
      - rk3
      - rk4
  coredns:
    enabled: true
  statefulSet:
    env:
      - name: LOFT_LOG_ENCODING
        value: json
      - name: LOFT_LOG_LEVEL
        value: warn
    resources:
      limits:
        ephemeral-storage: 2Gi
        memory: 2Gi
      requests:
        ephemeral-storage: 400Mi
        cpu: 200m
        memory: 256Mi
    highAvailability:
      replicas: 1
    security:
      podSecurityContext: {}
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
        runAsGroup: 0
    persistence:
      volumeClaim:
        enabled: auto
        retentionPolicy: Retain
        size: 2Gi
        storageClass: ""
        accessModes: ["ReadWriteOnce"]
exportKubeConfig:
  server: "https://rk1:8443"
  insecure: false
