controlPlane:
  distro:
    k3s:
      enabled: true
      extraArgs:
        - --tls-san=rpi --tls-san=rk1 --tls-san=rk2 --tls-san=rk3 --tls-san=rk4
        - --kube-apiserver-arg=oidc-issuer-url=https://accounts.google.com
        - --kube-apiserver-arg=oidc-client-id=613184563802-3ibtt184darm98idtv2kjcph6ol3nuga.apps.googleusercontent.com
      image:
        repository: rancher/k3s
        tag: v1.33.4-k3s1
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
  proxy:
    extraSANs:
      - rpi
      - rk1
      - rk2
      - rk3
      - rk4
  coredns:
    enabled: true
  statefulSet:
    image:
      registry: ghcr.io
      repository: loft-sh/vcluster-oss
      tag: 0.28.0
    env:
      - name: LOFT_LOG_ENCODING
        value: json
      - name: LOFT_LOG_LEVEL
        value: warn
    resources:
      limits:
        ephemeral-storage: 2Gi
        memory: 2Gi
      requests:
        ephemeral-storage: 400Mi
        cpu: 200m
        memory: 256Mi
    highAvailability:
      replicas: 1
    security:
      podSecurityContext: {}
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
        runAsGroup: 0
    persistence:
      volumeClaim:
        enabled: auto
        retentionPolicy: Retain
        size: 2Gi
        storageClass: ""
        accessModes: ["ReadWriteOnce"]
sync:
  toHost:
    ingresses:
      enabled: true
  fromHost:
    ingressClasses:
      enabled: true
exportKubeConfig:
  server: "https://rk1:8443"
  insecure: false
experimental:
  deploy:
    vcluster:
      manifests: |-
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: oidc-cluster-admin
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: https://accounts.google.com#105210177226998324921
