
# rewrite token and apply manualy
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  namespace: external-secrets
  labels:
    type: gitlab
type: Opaque
stringData:
  token: dummytoken
