apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-loki
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-loki
  storageClassName: celld-rgw
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-loki-ruler
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-loki-ruler
  storageClassName: celld-rgw
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-mimir-blocks
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-mimir-blocks
  storageClassName: celld-rgw
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-mimir-ruler
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-mimir-ruler
  storageClassName: celld-rgw
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-mimir-alertmanager
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-mimir-alertmanager
  storageClassName: celld-rgw
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-tempo
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-tempo
  storageClassName: celld-rgw
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-nisshi
  namespace: monitoring
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: observability-nisshi
  storageClassName: celld-rgw
