apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/nakatanakatana/mytools//config/litestream-controller/default?ref=v0.11.0
images:
  - name: ghcr.io/nakatanakatana/litestream-controller
    newTag: 0.11.0@sha256:8ca1fa5d6bc2f5a348d2f7081bdb134ce5e2df3f21648b76ecb3547df0eab092
