apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - celld
  - cloudflare-gateway-canary.yaml
  - feed-reader-debug/workload
  - nostr
  - nostr-nip05.yaml
  - obsidian-clippings-feed.yaml
  - feed-reader
