apiVersion: v1
kind: Namespace
metadata:
  name: nostr-nip05
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-nip05
  namespace: nostr-nip05
spec:
  selector:
    matchLabels:
      run: nostr-nip05
  replicas: 2
  template:
    metadata:
      labels:
        run: nostr-nip05
    spec:
      containers:
      - name: nostr-nip05
        image: ghcr.io/nakatanakatana/nip05:0.10.1@sha256:8f322c98c689a4061b279da06c6a0733fc3fa9bcc5652740c5a38e93dba1734f
        command: ["/app/nip05"]
        env:
        - name: NIP05_MAPPING
          value: _:513e9ab3e372f0484fdf7c1cb630fe195c344edc7e275f419c2b62fb9d749252
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nostr-nip05
  namespace: nostr-nip05
  labels:
    run: nostr-nip05
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: nostr-nip05
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cf-ingress-nostr-nip05
  namespace: nostr-nip05
spec:
  parentRefs:
    - name: cloudflare-app
      namespace: cloudflare-gateway
      sectionName: http
  hostnames:
    - nakatanakatana.app
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nostr-nip05
          port: 8080
