apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/install.yaml
  - ./crossplane/install.yaml
  - ./istio-system/install.yaml
  - ./keda/install.yaml
  - ./monitoring/install.yaml
