apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: avoid-slow-nodes
spec:
  statefulSet:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network
                operator: NotIn
                values:
                - slow
