apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: tailscale-operator
      version: '1.80.0'
      sourceRef:
        kind: HelmRepository
        name: tailscale
  releaseName: tailscale
  valuesFrom:
    - kind: Secret
      name: tailscale-client
      targetPath: oauth.clientId
      valuesKey: client_id
    - kind: Secret
      name: tailscale-client
      targetPath: oauth.clientSecret
      valuesKey: client_secret
