apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alerts-external-secret
  namespace: flux-system
spec:
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: slack-bot-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: slack-bot-alert/bot-token
