apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-gateway-token
  namespace: cloudflare-gateway
spec:
  refreshInterval: 19h14m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: cloudflare-gateway-token
    creationPolicy: Owner
  data:
    - secretKey: ACCOUNT_ID
      remoteRef:
        key: cloudflare/account_id
    - secretKey: TOKEN
      remoteRef:
        key: cloudflare/api_token
