apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cloudflare-tunnel-ingress
spec:
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: cloudflare-external-secret
    creationPolicy: Owner
  data:
    - secretKey: account_id
      remoteRef:
        key: cloudflare/account_id
    - secretKey: api_token
      remoteRef:
        key: cloudflare/api_token
    - secretKey: tunnel_name
      remoteRef:
        key: cloudflare/tunnel_name

