apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-secret
  namespace: monitoring
spec:
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: grafana-cloud-secret
    creationPolicy: Owner
  data:
    - secretKey: prom_user
      remoteRef:
        key: grafana-cloud/prom_user
    - secretKey: loki_user
      remoteRef:
        key: grafana-cloud/loki_user
    - secretKey: tempo_user
      remoteRef:
        key: grafana-cloud/tempo_user
    - secretKey: password
      remoteRef:
        key: grafana-cloud/password
