apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llama-cpp-secret
  namespace: llama-cpp
spec:
  refreshInterval: 20h16m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: llama-cpp-secret
    creationPolicy: Owner
  data:
    - secretKey: HUGGING_FACE_HUB_TOKEN
      remoteRef:
        key: huggingface/token
