apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neon-s3-credentials
  namespace: database
spec:
  refreshInterval: 18h43m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: neon-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: pcloud-s3/S3_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: pcloud-s3/S3_SECRET_ACCESS_KEY
