apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-secret
  namespace: default
spec:
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: obsidian-secret
    creationPolicy: Owner
    template:
      data:
        config.json: "{{ .config }}"
  data:
    - secretKey: config
      remoteRef:
        key: obsidian-livesync/config
