apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-secret
  namespace: tailscale
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: tailscale-client
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale/client_id
    - secretKey: client_secret
      remoteRef:
        key: tailscale/client_secret

