apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: external-secrets
      version: '0.14.3'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  releaseName: external-secrets

