apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 1h0m0s
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
