platform: k8s
nodeSelector:
  kubernetes.io/hostname: n5
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node.kubernetes.io/disk-pressure
    operator: Exists
    effect: NoSchedule
kubelet:
  podResourceAPISocketPath: /var/lib/kubelet/pod-resources
monitor:
  resources:
    gpu: true
    nic: false
image:
  repository: docker.io/rocm/device-metrics-exporter
  tag: v1.5.1@sha256:cbef5772c435d648ebd6de705517c4978efdb4b5650952c6797cc2bf15af747a
  pullPolicy: IfNotPresent
priorityClassName: system-node-critical
service:
  type: ClusterIP
  ClusterIP:
    port: 5000
serviceMonitor:
  enabled: true
  interval: 30s
  honorLabels: true
  honorTimestamps: true
  metricRelabelings:
    - action: keep
      sourceLabels:
        - __name__
      regex: '^amd_gpu_(gfx_activity|umc_activity|used_vram|total_vram)$'
