apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: cloudflare-tunnel-ingress
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: cloudflare-tunnel-ingress
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
