apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: cert-manager
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: cert-manager
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
