apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: cert-manager
      version: 'v1.19.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  releaseName: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager

