apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-configs
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/home/configs
  dependsOn:
    - name: flux-system
    - name: external-secrets
    - name: cert-manager
  prune: true
  timeout: 1m
