---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-systems
  labels:
    name: arc-systems
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel-ingress
  labels:
    name: cloudflare-tunnel-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: couchdb
  labels:
    name: couchdb
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
  labels:
    name: postgres-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    name: sandbox
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    name: tailscale
