apiVersion: apps/v1
kind: Deployment
metadata:
  name: bifrost
  namespace: proxy
  labels:
    app: bifrost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bifrost
  template:
    metadata:
      labels:
        app: bifrost
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network
                    operator: NotIn
                    values:
                      - slow
      containers:
        - name: bifrost
          image: ghcr.io/maximhq/bifrost:v1.6.5@sha256:b889699abe8baa78e493e03307cb90551468998699422712e25468a41a252f28
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: BIFROST_LOG_LEVEL
              value: "info"
          envFrom:
            - secretRef:
                name: bifrost-secret
          volumeMounts:
            - name: config-volume
              mountPath: /app/data/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: bifrost-config
