apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bifrost
  namespace: proxy
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: bifrost
      version: '2.1.31'
      sourceRef:
        kind: HelmRepository
        name: bifrost
        namespace: proxy
  releaseName: bifrost
  values:
    image:
      tag: v1.5.12
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    storage:
      persistence:
        size: 1Gi
    bifrost:
      logLevel: warn
      client:
        enforceAuthOnInference: false
      providers:
        openai:
          keys:
            - name: primary
              value: env.OPENAI_API_KEY
              weight: 1
          network_config:
            base_url: env.OPENAI_BASE_URL
    envFrom:
      - secretRef:
          name: bifrost-secret
