apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secret
  namespace: cloudflare-tunnel-ingress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: cloudflare-external-secret
    creationPolicy: Owner
  data:
    - secretKey: account_id
      remoteRef:
        key: cf_account_id
    - secretKey: api_token
      remoteRef:
        key: cf_api_token
    - secretKey: tunnel_name
      remoteRef:
        key: cf_tunnel_name

