apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dummy-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: dummy-secret
    creationPolicy: Owner
  data:
    - secretKey: key1
      remoteRef:
        key: key1
    - secretKey: key2
      remoteRef:
        key: key2
