apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dummy-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store
  target:
    name: gitlab-secret-to-create
    creationPolicy: Owner
  data:
    - secretKey: secret-key1
      remoteRef:
        key: key1
    - secretKey: secret-key2
      remoteRef:
        key: key2
