apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: grafana-cloud-secret
    creationPolicy: Owner
  data:
    - secretKey: prom_user
      remoteRef:
        key: gc_prom_user
    - secretKey: loki_user
      remoteRef:
        key: gc_loki_user
    - secretKey: tempo_user
      remoteRef:
        key: gc_tempo_user
    - secretKey: password
      remoteRef:
        key: gc_password
