apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: obsidian-secret
    creationPolicy: Owner
    template:
      data:
        config.json: "{{ .config }}"
  data:
    - secretKey: config
      remoteRef:
        key: livesync_bridge_config
