apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vcluster-secret
  namespace: vcluster
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: vcluster-db
    creationPolicy: Owner
  data:
    - secretKey: db
      remoteRef:
        key: vc_vcluster_db
