apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: rook-ceph
      version: 'v1.18.6'
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  releaseName: rook-ceph
  valuesFrom:
    - kind: ConfigMap
      name: rook-ceph

