apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: k8s-monitoring
      version: '3.4.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
  releaseName: grafana-k8s-monitoring
  valuesFrom:
    - kind: ConfigMap
      name: k8s-monitoring

