cluster:
  name: home-k3s
externalServices:
  prometheus:
    hostKey: prom_host
    secret:
      create: false
      name: grafana-cloud-secret
      namespace: monitoring
    basicAuth:
      usernameKey: prom_user
      passwordKey: password
  loki:
    hostKey: loki_host
    secret:
      create: false
      name: grafana-cloud-secret
      namespace: monitoring
    basicAuth:
      usernameKey: loki_user
      passwordKey: password
  tempo:
    hostKey;: tempo_host
    secret:
      create: false
      name: grafana-cloud-secret
      namespace: monitoring
    basicAuth:
      usernameKey: tempo_user
      passwordKey: password
metrics:
  enabled: true
  podMonitors:
    enabled: true
  alloy:
    metricsTuning:
      useIntegrationAllowList: true
  cost:
    enabled: false
  kepler:
    enabled: false
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
  grafanaCloudMetrics:
    enabled: false
opencost:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
kepler:
  enabled: false
alloy: {}
alloy-events: {}
alloy-logs: {}
