apiVersion: v1
kind: Service
metadata:
  name: observability-local-alloy
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: observability-local-alloy
  ports:
    - name: http
      port: 12345
      targetPort: http
      protocol: TCP
