apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: vcluster
resources:
  - ../base/namespace.yaml
  - ../base/repository.yaml
  - release.yaml
  - ../base/lb.yaml
configMapGenerator:
  - name: vcluster
    files:
      - values.yaml=../base/values.yaml
  - name: vcluster-policy
    files:
      - values.yaml=../base/policy-values.yaml
configurations:
  - ../base/kustomizeconfig.yaml
