apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-systems
  namespace: arc-systems
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: arc-systems-controller
    namespace: arc-systems
