apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb
  namespace: couchdb
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      interval: 10m
      chart: couchdb
      version: '4.6.1'
      sourceRef:
        kind: HelmRepository
        name: couchdb
  releaseName: couchdb
  valuesFrom:
    - kind: ConfigMap
      name: couchdb

