persistentVolume:
  enabled: true

couchdbConfig:
  couchdb:
    uuid: aedeb892-206b-4b69-bbf7-a0e315adf960
    max_document_size: 50000000
  chttpd:
    require_valid_user: true
    max_http_request_size: 4294967296
  chttpd_auth:
    require_valid_user: true
    authentication_redirect: /_utils/session.html
  httpd:
    WWW-Authenticate: Basic realm="couchdb"
    enable_cors: true
  cors: 
    origins: app://obsidian.md,capacitor://localhost,http://localhost
    credentials: true
    headers: accept, authorization, content-type, origin, referer
    methods: GET, PUT, POST, HEAD, DELETE
    max_age: 3600
