apiVersion: v1
kind: Service
metadata:
  name: llama-cpp
  namespace: llama-cpp
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "llama-cpp"
  labels:
    app.kubernetes.io/name: llama-cpp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: llama-cpp
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
